.PHONY: build

CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER := x86_64-linux-gnu-gcc
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER

build:
	cargo build --target x86_64-unknown-linux-gnu --release
